name: 'chicago_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'chicago_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models with bronze/silver architecture
models:
  chicago_analytics:
    # Bronze layer - raw data ingestion
    bronze:
      +materialized: view
      +schema: bronze
    # Silver layer - cleaned and standardized data
    silver:
      +materialized: view
      +schema: silver

# Configuring seeds
seeds:
  chicago_analytics:
    +column_types:
      id: integer
      created_at: timestamp

# Configuring snapshots
snapshots:
  chicago_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Configuring tests
tests:
  +store_failures: false
  +severity: warn
