-- 1. Drop role if it exists (optional, only if you want to overwrite)
DROP ROLE IF EXISTS TABLEAU_USER_ROLE_TEST;

-- 2. Create the role
CREATE ROLE TABLEAU_USER_ROLE_TEST;

-- 3. Grant warehouse usage (so queries can run)
GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE TABLEAU_USER_ROLE_TEST;

-- 4. Grant database usage
GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE TABLEAU_USER_ROLE_TEST;

-- 5. Grant schema usage
GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.WORKSHOP_GOLD TO ROLE TABLEAU_USER_ROLE_TEST;

-- 6. Grant read-only access to existing tables/views in schema
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_LEARNING_DB.WORKSHOP_GOLD TO ROLE TABLEAU_USER_ROLE_TEST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_LEARNING_DB.WORKSHOP_GOLD TO ROLE TABLEAU_USER_ROLE_TEST;

-- 7. Ensure future objects are also accessible
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE_LEARNING_DB.WORKSHOP_GOLD TO ROLE TABLEAU_USER_ROLE_TEST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWFLAKE_LEARNING_DB.WORKSHOP_GOLD TO ROLE TABLEAU_USER_ROLE_TEST;